@echo off
cd /d E:\my\project_p\party_link
echo [1/4] flutter clean...
flutter clean
echo [2/4] build 폴더 삭제...
rd /s /q build 2>nul
echo [3/4] flutter pub get...
flutter pub get
echo [4/4] flutter run...
flutter run -d chrome --web-port 8080
